[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smclip"
version = "0.1.0"
description = "Smart Clipboard CLI manager"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "rich",
    "prompt_toolkit"
]

[project.scripts]
smclip = "main:main"

[tool.setuptools]
py-modules = ["main", "logic"]
